name: Build Docker - mediasoup-demo 

on: 
  push:
    branches:
    - 'main'

env:
  IMAGE_NAME: mediasoup-demo
  DOCKERFILE_PATH: ./

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set IMAGE_TAG env # env IMAGE_TAG=BranchName-CommitID-Timestamp
      run: echo IMAGE_TAG=$(basename ${GITHUB_REF})-$(echo ${GITHUB_SHA} | cut -c 1-7)-$(date -u +"%Y%m%d") >> ${GITHUB_ENV}
    - name: Environment Printer
      uses: managedkaos/print-env@v1.0

    # - name: Prepare config
    #   run: cd server && cp config.example.js config.js
    # - name: Prepare Certs
    #   run: cd server && mkdir -p certs && cd certs && openssl genrsa > privkey.pem && openssl req -new -x509 -key privkey.pem -subj "/C=CN/ST=SH/L=Springfield/O=Dis/CN=www.example.com" > fullchain.pem

    - name: Build & Publish to Github Container Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: ${{ github.actor }}/${{ env.IMAGE_NAME }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        snapshot: false
        workdir: ${{ env.DOCKERFILE_PATH }}
        tags: "latest,${{ env.IMAGE_TAG }}"
        buildargs: "IMAGE_TAG=${{ env.IMAGE_TAG }}"

  copy-to-tencentyun-hk:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: onichandame/docker-registry-sync-action@master
      with:
        source_repository: ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest
        target_repository: hkccr.ccs.tencentyun.com/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest
        target_username: ${{ secrets.TENCENTYUN_DOCKER_REGISTRY_USERNAME }}
        target_password: ${{ secrets.TENCENTYUN_DOCKER_REGISTRY_PASSWORD }}
